/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 *
 * HDF is dual licensed: you can use it either under the terms of
 * the GPL, or the BSD license, at your option.
 * See the LICENSE file in the root of this repository for complete details.
 */

#ifndef AUDIO_COMMON_TEST_H
#define AUDIO_COMMON_TEST_H

#include "hdf_types.h"

const int32_t g_testAudioType = 701; // 701 is TEST_AUDIO_TYPE

enum {
    TESTGETCODEC,
    TESTGETCARDINSTANCE,
    TESTGETCCNFIGDATA,

    TESTREGISTERPLATFORM,
    TESTREGISTERDAI,
    TESTREGISTERACCESSORY,
    TESTREGISTERCODEC,
    TESTREGISTERDSP,
    TESTSOCDEVICEREGISTER,
    TESTBINDDAILINK,
    TESTUPDATECODECREGBITS,
    TESTUPDATEACCESSORYREGBITS,
    TESTKCONTROLGETCODEC,
    TESTKCONTROLGETACCESSORY,
    TESTADDCONTROL,
    TESTADDCONTROLS,
    TESTCODECREADREG,
    TESTACCESSORYREADREG,
    TESTCODECWRITEREG,
    TESTACCESSORYWRITEREG,
    TESTINFOCTRLOPS,
    TESTCODECGETCTRLOPS,
    TESTACCESSORYGETCTRLOPS,
    TESTCODECSETCTRLOPS,
    TESTACCESSORYSETCTRLOPS,

    TESTNEWCOMPONENT,
    TESTADDROUTES,
    TESTNEWCONTROLS,
    TESTPOWERCOMPONET,
    TESTREFRESHTIME,
    TESTSTREAMDISPATCH,
};

#endif /* AUDIO_COMMON_TEST_H */
