/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 *
 * HDF is dual licensed: you can use it either under the terms of
 * the GPL, or the BSD license, at your option.
 * See the LICENSE file in the root of this repository for complete details.
 */

#ifndef HDF_AUDIO_TEST_H
#define HDF_AUDIO_TEST_H

#include "hdf_main_test.h"

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif /* __cplusplus */

typedef enum {
    AUDIO_DRIVER_TESTGETCODEC,
    AUDIO_DRIVER_TESTGETCARDINSTANCE,
    AUDIO_DRIVER_TESTGETCCNFIGDATA,
    AUDIO_DRIVER_TESTREGISTERPLATFORM,
    AUDIO_DRIVER_TESTREGISTERDAI,
    AUDIO_DRIVER_TESTREGISTERACCESSORY,
    AUDIO_DRIVER_TESTREGISTERCODEC,
    AUDIO_DRIVER_TESTREGISTERDSP,
    AUDIO_DRIVER_TESTSOCDEVICEREGISTER,
    AUDIO_DRIVER_TESTBINDDAILINK,
    AUDIO_DRIVER_TESTUPDATECODECREGBITS,
    AUDIO_DRIVER_TESTUPDATEACCESSORYREGBITS,
    AUDIO_DRIVER_TESTUPDATECODECAIAOREGBITS,
    AUDIO_DRIVER_TESTUPDATEACCESSORYAIAOREGBITS,
    AUDIO_DRIVER_TESTKCONTROLGETCODEC,
    AUDIO_DRIVER_TESTKCONTROLGETACCESSORY,
    AUDIO_DRIVER_TESTADDCONTROL,
    AUDIO_DRIVER_TESTADDCONTROLS,
    AUDIO_DRIVER_TESTCODECREADREG,
    AUDIO_DRIVER_TESTACCESSORYREADREG,
    AUDIO_DRIVER_TESTCODECAIAOREADREG,
    AUDIO_DRIVER_TESTACCESSORYAIAOREADREG,
    AUDIO_DRIVER_TESTCODECWRITEREG,
    AUDIO_DRIVER_TESTACCESSORYWRITEREG,
    AUDIO_DRIVER_TESTCODECAIAOWRITEREG,
    AUDIO_DRIVER_TESTACCESSORYAIAOWRITEREG,
    AUDIO_DRIVER_TESTINFOCTRLOPS,
    AUDIO_DRIVER_TESTCODECGETCTRLOPS,
    AUDIO_DRIVER_TESTACCESSORYGETCTRLOPS,
    AUDIO_DRIVER_TESTCODECAIAOGETCTRLOPS,
    AUDIO_DRIVER_TESTACCESSORYAIAOGETCTRLOPS,
    AUDIO_DRIVER_TESTCODECSETCTRLOPS,
    AUDIO_DRIVER_TESTACCESSORYSETCTRLOPS,
    AUDIO_DRIVER_TESTCODECAIAOSETCTRLOPS,
    AUDIO_DRIVER_TESTACCESSORYAIAOSETCTRLOPS,
    AUDIO_DRIVER_TESTNEWCOMPONENT,
    AUDIO_DRIVER_TESTADDROUTES,
    AUDIO_DRIVER_TESTNEWCONTROLS,
    AUDIO_DRIVER_TESTPOWERCOMPONET,
    AUDIO_DRIVER_TESTREFRESHTIME,
    AUDIO_DRIVER_TESTSTREAMDISPATCH,
} HdfAudioTestCaseCmd;

int32_t HdfAudioEntry(HdfTestMsg *msg);

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* __cplusplus */

#endif /* HDF_AUDIO_TEST_H */
