/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 *
 * HDF is dual licensed: you can use it either under the terms of
 * the GPL, or the BSD license, at your option.
 * See the LICENSE file in the root of this repository for complete details.
 */

#ifndef HDF_AUDIO_TEST_H
#define HDF_AUDIO_TEST_H

#include "hdf_main_test.h"

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif /* __cplusplus */

typedef enum {
    AUDIO_DRIVER_TESTGETCODEC,
    AUDIO_DRIVER_TESTGETCARDINSTANCE,
    AUDIO_DRIVER_TESTHOSTDESTROY,
    AUDIO_DRIVER_TESTGETCCNFIGDATA,
    AUDIO_DRIVER_TESTREGISTERDAI,
    AUDIO_DRIVER_TESTREGISTERPLATFORM,
    AUDIO_DRIVER_TESTREGISTERCODEC,
    AUDIO_DRIVER_TESTBINDDAILINK,
    AUDIO_DRIVER_TESTDEVICEREGISTER,
    AUDIO_DRIVER_TESTREGISTERDSP,
    AUDIO_DRIVER_TESTREGISTERACCESSORY,
    AUDIO_DRIVER_TESTUPDATEREGBITS,
    AUDIO_DRIVER_TESTAIAOUPDATEREGBITS,
    AUDIO_DRIVER_TESTKCONTROLGETCODEC,
    AUDIO_DRIVER_TESTADDCONTROLS,
    AUDIO_DRIVER_TESTADDCONTROL,
    AUDIO_DRIVER_TESTDEVICEREADREG,
    AUDIO_DRIVER_TESTAIAODEVICEREADREG,
    AUDIO_DRIVER_TESTINFOCTRLSW,
    AUDIO_DRIVER_TESTGETCTRLSW,
    AUDIO_DRIVER_TESTPUTCTRLSW,
    AUDIO_DRIVER_TESTAIAOGETCTRLSW,
    AUDIO_DRIVER_TESTAIAOPUTCTRLSW,
    AUDIO_DRIVER_TESTNEWCOMPONENT,
    AUDIO_DRIVER_TESTADDROUTES,
    AUDIO_DRIVER_TESTNEWCONTROLS,
    AUDIO_DRIVER_TESTPOWERCOMPONET,
    AUDIO_DRIVER_TESTREFRESHTIME,
    AUDIO_DRIVER_TESTSTREAMDISPATCH,
    AUDIO_DRIVER_TESTSTREAMDESTORY,
} HdfAudioTestCaseCmd;

int32_t HdfAudioEntry(HdfTestMsg *msg);

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* __cplusplus */

#endif /* HDF_AUDIO_TEST_H */
